# These are supported funding model platforms

github: hakxcore
patreon: hakxcore
open_collective: hakxcore
ko_fi: hakxcore
tidelift: hakxcore
community_bridge: hakxcore
liberapay: hakxcore
issuehunt: hakxcore
otechie: hakxcore
custom: hakxcore
